/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of HMM.xs. Do not edit this file, edit HMM.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "HMM.xs"
#ifdef __cplusplus
extern "C" {
#endif

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#ifdef __cplusplus
}
#endif

#include "hmm.h"
#include "globals.h"

HMM *hmm_new(char *filename, int df, int n2) {

  return new HMM(filename, df, n2);
}

HMMReport *hmm_report_new() {

  return new HMMReport();
}

HMMDomainHit *hmm_domain_hit_new(float s, double p, double e) {

  return new HMMDomainHit(s, p, e);
}

HMMGlobalHit *hmm_global_hit_new(float s, double p, double e) {

  return new HMMGlobalHit(s, p, e);
}


#line 47 "HMM.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 99 "HMM.c"

XS(XS_Algorithm__HMM__Hit__Domain_hmm_domain_hit_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain_hmm_domain_hit_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "s, p, e");
    {
	float	s = (float)SvNV(ST(0));
	double	p = (double)SvNV(ST(1));
	double	e = (double)SvNV(ST(2));
	HMMDomainHit *	RETVAL;

	RETVAL = hmm_domain_hit_new(s, p, e);
	ST(0) = sv_newmortal();
	if( RETVAL == NULL )	XSRETURN_UNDEF;
	sv_setref_pv( ST(0), "Algorithm::HMM::Hit::Domain", (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Domain__getPValue); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__getPValue)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMDomainHit *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_getPValue() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 48 "HMM.xs"
        RETVAL = THIS->getPValue();
#line 150 "HMM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Domain__setPValue); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__setPValue)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	HMMDomainHit *	THIS;
	double	i = (double)SvNV(ST(1));

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_setPValue() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 55 "HMM.xs"
        THIS->setPValue(i);
#line 179 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Hit__Domain__getEValue); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__getEValue)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMDomainHit *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_getEValue() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 60 "HMM.xs"
        RETVAL = THIS->getEValue();
#line 208 "HMM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Domain__setEValue); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__setEValue)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	HMMDomainHit *	THIS;
	double	i = (double)SvNV(ST(1));

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_setEValue() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 67 "HMM.xs"
        THIS->setEValue(i);
#line 237 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Hit__Domain__getScore); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__getScore)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMDomainHit *	THIS;
	float	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_getScore() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 72 "HMM.xs"
        RETVAL = THIS->getScore();
#line 266 "HMM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Domain__setScore); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__setScore)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	HMMDomainHit *	THIS;
	float	i = (float)SvNV(ST(1));

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_setScore() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 79 "HMM.xs"
        THIS->setScore(i);
#line 295 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Hit__Domain__getSeqFrom); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__getSeqFrom)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMDomainHit *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_getSeqFrom() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 84 "HMM.xs"
        RETVAL = THIS->getSeqFrom();
#line 324 "HMM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Domain__setSeqFrom); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__setSeqFrom)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	int	i = (int)SvIV(ST(1));
	HMMDomainHit *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_setSeqFrom() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 92 "HMM.xs"
        THIS->setSeqFrom(i);
#line 353 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Hit__Domain__getSeqTo); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__getSeqTo)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMDomainHit *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_getSeqTo() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 97 "HMM.xs"
        RETVAL = THIS->getSeqTo();
#line 382 "HMM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Domain__setSeqTo); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__setSeqTo)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	int	i = (int)SvIV(ST(1));
	HMMDomainHit *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_setSeqTo() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 105 "HMM.xs"
        THIS->setSeqTo(i);
#line 411 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Hit__Domain__getSeqLength); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__getSeqLength)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMDomainHit *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_getSeqLength() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 110 "HMM.xs"
        RETVAL = THIS->getSeqLength();
#line 440 "HMM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Domain__setSeqLength); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__setSeqLength)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	int	i = (int)SvIV(ST(1));
	HMMDomainHit *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_setSeqLength() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 118 "HMM.xs"
        THIS->setSeqLength(i);
#line 469 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Hit__Domain__getHMMFrom); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__getHMMFrom)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMDomainHit *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_getHMMFrom() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 123 "HMM.xs"
        RETVAL = THIS->getHMMFrom();
#line 498 "HMM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Domain__setHMMFrom); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__setHMMFrom)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	int	i = (int)SvIV(ST(1));
	HMMDomainHit *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_setHMMFrom() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 131 "HMM.xs"
        THIS->setHMMFrom(i);
#line 527 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Hit__Domain__getHMMTo); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__getHMMTo)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMDomainHit *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_getHMMTo() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 136 "HMM.xs"
        RETVAL = THIS->getHMMTo();
#line 556 "HMM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Domain__setHMMTo); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__setHMMTo)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	int	i = (int)SvIV(ST(1));
	HMMDomainHit *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_setHMMTo() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 144 "HMM.xs"
        THIS->setHMMTo(i);
#line 585 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Hit__Domain__getParentPValue); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__getParentPValue)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMDomainHit *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_getParentPValue() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 149 "HMM.xs"
        RETVAL = THIS->getParentPValue();
#line 614 "HMM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Domain__setParentPValue); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__setParentPValue)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	double	i = (double)SvNV(ST(1));
	HMMDomainHit *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_setParentPValue() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 157 "HMM.xs"
        THIS->setParentPValue(i);
#line 643 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Hit__Domain__getParentEValue); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__getParentEValue)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMDomainHit *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_getParentEValue() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 162 "HMM.xs"
        RETVAL = THIS->getParentEValue();
#line 672 "HMM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Domain__setParentEValue); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__setParentEValue)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	double	i = (double)SvNV(ST(1));
	HMMDomainHit *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_setParentEValue() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 170 "HMM.xs"
        THIS->setParentEValue(i);
#line 701 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Hit__Domain__getParentScore); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__getParentScore)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMDomainHit *	THIS;
	float	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_getParentScore() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 175 "HMM.xs"
        RETVAL = THIS->getParentScore();
#line 730 "HMM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Domain__setParentScore); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Domain__setParentScore)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	float	i = (float)SvNV(ST(1));
	HMMDomainHit *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Domain") ) {
		THIS = (HMMDomainHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Domain::_setParentScore() -- THIS is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};
#line 183 "HMM.xs"
        THIS->setParentScore(i);
#line 759 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Hit__Global_hmm_global_hit_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Global_hmm_global_hit_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "s, p, e");
    {
	float	s = (float)SvNV(ST(0));
	double	p = (double)SvNV(ST(1));
	double	e = (double)SvNV(ST(2));
	HMMGlobalHit *	RETVAL;

	RETVAL = hmm_global_hit_new(s, p, e);
	ST(0) = sv_newmortal();
	if( RETVAL == NULL )	XSRETURN_UNDEF;
	sv_setref_pv( ST(0), "Algorithm::HMM::Hit::Global", (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Global__getPValue); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Global__getPValue)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMGlobalHit *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Global") ) {
		THIS = (HMMGlobalHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Global::_getPValue() -- THIS is not an Algorithm::HMM::Hit::Global object" );
		XSRETURN_UNDEF;
	};
#line 197 "HMM.xs"
        RETVAL = THIS->getPValue();
#line 814 "HMM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Global__setPValue); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Global__setPValue)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	HMMGlobalHit *	THIS;
	double	i = (double)SvNV(ST(1));

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Global") ) {
		THIS = (HMMGlobalHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Global::_setPValue() -- THIS is not an Algorithm::HMM::Hit::Global object" );
		XSRETURN_UNDEF;
	};
#line 204 "HMM.xs"
        THIS->setPValue(i);
#line 843 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Hit__Global__getEValue); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Global__getEValue)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMGlobalHit *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Global") ) {
		THIS = (HMMGlobalHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Global::_getEValue() -- THIS is not an Algorithm::HMM::Hit::Global object" );
		XSRETURN_UNDEF;
	};
#line 209 "HMM.xs"
        RETVAL = THIS->getEValue();
#line 872 "HMM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Global__setEValue); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Global__setEValue)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	HMMGlobalHit *	THIS;
	double	i = (double)SvNV(ST(1));

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Global") ) {
		THIS = (HMMGlobalHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Global::_setEValue() -- THIS is not an Algorithm::HMM::Hit::Global object" );
		XSRETURN_UNDEF;
	};
#line 216 "HMM.xs"
        THIS->setEValue(i);
#line 901 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Hit__Global__getScore); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Global__getScore)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMGlobalHit *	THIS;
	float	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Global") ) {
		THIS = (HMMGlobalHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Global::_getScore() -- THIS is not an Algorithm::HMM::Hit::Global object" );
		XSRETURN_UNDEF;
	};
#line 221 "HMM.xs"
        RETVAL = THIS->getScore();
#line 930 "HMM.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Hit__Global__setScore); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Hit__Global__setScore)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	HMMGlobalHit *	THIS;
	float	i = (float)SvNV(ST(1));

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Hit::Global") ) {
		THIS = (HMMGlobalHit *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Hit::Global::_setScore() -- THIS is not an Algorithm::HMM::Hit::Global object" );
		XSRETURN_UNDEF;
	};
#line 228 "HMM.xs"
        THIS->setScore(i);
#line 959 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Report_hmm_report_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Report_hmm_report_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	HMMReport *	RETVAL;

	RETVAL = hmm_report_new();
	ST(0) = sv_newmortal();
	if( RETVAL == NULL )	XSRETURN_UNDEF;
	sv_setref_pv( ST(0), "Algorithm::HMM::Report", (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Report__addGlobalHit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Report__addGlobalHit)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, h");
    {
	HMMGlobalHit *	h;
	HMMReport *	THIS;

	if( sv_isobject(ST(1)) && sv_isa(ST(1), "Algorithm::HMM::Hit::Global") ) {
		h = (HMMGlobalHit *)SvIV((SV*)SvRV( ST(1) ));
	} else {
		warn( "Algorithm::HMM::Report::_addGlobalHit() -- h is not an Algorithm::HMM::Hit::Global object" );
		XSRETURN_UNDEF;
	};

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Report") ) {
		THIS = (HMMReport *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Report::_addGlobalHit() -- THIS is not an Algorithm::HMM::Report object" );
		XSRETURN_UNDEF;
	};
#line 240 "HMM.xs"
        THIS->addGlobalHit(h);
#line 1017 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Report__numGlobalHits); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Report__numGlobalHits)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMReport *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Report") ) {
		THIS = (HMMReport *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Report::_numGlobalHits() -- THIS is not an Algorithm::HMM::Report object" );
		XSRETURN_UNDEF;
	};
#line 245 "HMM.xs"
        RETVAL = THIS->numGlobalHits();
#line 1046 "HMM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Report__getGlobalHit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Report__getGlobalHit)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	int	i = (int)SvIV(ST(1));
	HMMReport *	THIS;
	HMMGlobalHit *	RETVAL;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Report") ) {
		THIS = (HMMReport *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Report::_getGlobalHit() -- THIS is not an Algorithm::HMM::Report object" );
		XSRETURN_UNDEF;
	};
#line 253 "HMM.xs"
        RETVAL = THIS->getGlobalHit(i);
#line 1076 "HMM.c"
	ST(0) = sv_newmortal();
	if( RETVAL == NULL )	XSRETURN_UNDEF;
	sv_setref_pv( ST(0), "Algorithm::HMM::Hit::Global", (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Report__addDomainHit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Report__addDomainHit)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, h");
    {
	HMMDomainHit *	h;
	HMMReport *	THIS;

	if( sv_isobject(ST(1)) && sv_isa(ST(1), "Algorithm::HMM::Hit::Domain") ) {
		h = (HMMDomainHit *)SvIV((SV*)SvRV( ST(1) ));
	} else {
		warn( "Algorithm::HMM::Report::_addDomainHit() -- h is not an Algorithm::HMM::Hit::Domain object" );
		XSRETURN_UNDEF;
	};

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Report") ) {
		THIS = (HMMReport *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Report::_addDomainHit() -- THIS is not an Algorithm::HMM::Report object" );
		XSRETURN_UNDEF;
	};
#line 261 "HMM.xs"
        THIS->addDomainHit(h);
#line 1115 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__Report__numDomainHits); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Report__numDomainHits)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMReport *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Report") ) {
		THIS = (HMMReport *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Report::_numDomainHits() -- THIS is not an Algorithm::HMM::Report object" );
		XSRETURN_UNDEF;
	};
#line 266 "HMM.xs"
        RETVAL = THIS->numDomainHits();
#line 1144 "HMM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Report__getDomainHit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Report__getDomainHit)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, i");
    {
	int	i = (int)SvIV(ST(1));
	HMMReport *	THIS;
	HMMDomainHit *	RETVAL;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Report") ) {
		THIS = (HMMReport *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Report::_getDomainHit() -- THIS is not an Algorithm::HMM::Report object" );
		XSRETURN_UNDEF;
	};
#line 274 "HMM.xs"
        RETVAL = THIS->getDomainHit(i);
#line 1174 "HMM.c"
	ST(0) = sv_newmortal();
	if( RETVAL == NULL )	XSRETURN_UNDEF;
	sv_setref_pv( ST(0), "Algorithm::HMM::Hit::Domain", (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__Report_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__Report_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMMReport *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM::Report") ) {
		THIS = (HMMReport *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::Report::DESTROY() -- THIS is not an Algorithm::HMM::Report object" );
		XSRETURN_UNDEF;
	};

	delete THIS;
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM_hmm_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM_hmm_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "filename, df, n2");
    {
	char *	filename = (char *)SvPV_nolen(ST(0));
	int	df = (int)SvIV(ST(1));
	int	n2 = (int)SvIV(ST(2));
	HMM *	RETVAL;

	RETVAL = hmm_new(filename, df, n2);
	ST(0) = sv_newmortal();
	if( RETVAL == NULL )	XSRETURN_UNDEF;
	sv_setref_pv( ST(0), "Algorithm::HMM", (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__save); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__save)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "THIS, filename, append, binary");
    {
	char *	filename = (char *)SvPV_nolen(ST(1));
	int	append = (int)SvIV(ST(2));
	int	binary = (int)SvIV(ST(3));
	HMM *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM") ) {
		THIS = (HMM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::_save() -- THIS is not an Algorithm::HMM object" );
		XSRETURN_UNDEF;
	};
#line 295 "HMM.xs"
        RETVAL = THIS->save(filename, append, binary);
#line 1262 "HMM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__load); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__load)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, filename");
    {
	char *	filename = (char *)SvPV_nolen(ST(1));
	HMM *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM") ) {
		THIS = (HMM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::_load() -- THIS is not an Algorithm::HMM object" );
		XSRETURN_UNDEF;
	};
#line 303 "HMM.xs"
        RETVAL = THIS->load(filename);
#line 1293 "HMM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__modelLoaded); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__modelLoaded)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMM *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM") ) {
		THIS = (HMM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::_modelLoaded() -- THIS is not an Algorithm::HMM object" );
		XSRETURN_UNDEF;
	};
#line 310 "HMM.xs"
        RETVAL = THIS->modelLoaded();
#line 1323 "HMM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__getDoForward); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__getDoForward)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMM *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM") ) {
		THIS = (HMM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::_getDoForward() -- THIS is not an Algorithm::HMM object" );
		XSRETURN_UNDEF;
	};
#line 317 "HMM.xs"
        RETVAL = THIS->getDoForward();
#line 1353 "HMM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__setDoForward); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__setDoForward)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, df");
    {
	int	df = (int)SvIV(ST(1));
	HMM *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM") ) {
		THIS = (HMM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::_setDoForward() -- THIS is not an Algorithm::HMM object" );
		XSRETURN_UNDEF;
	};
#line 325 "HMM.xs"
        THIS->setDoForward(df);
#line 1382 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__getDoNull2); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__getDoNull2)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMM *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM") ) {
		THIS = (HMM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::_getDoNull2() -- THIS is not an Algorithm::HMM object" );
		XSRETURN_UNDEF;
	};
#line 330 "HMM.xs"
        RETVAL = THIS->getDoNull2();
#line 1411 "HMM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__setDoNull2); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__setDoNull2)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, n2");
    {
	int	n2 = (int)SvIV(ST(1));
	HMM *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM") ) {
		THIS = (HMM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::_setDoNull2() -- THIS is not an Algorithm::HMM object" );
		XSRETURN_UNDEF;
	};
#line 338 "HMM.xs"
        THIS->setDoNull2(n2);
#line 1440 "HMM.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Algorithm__HMM__search); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__search)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, seq");
    {
	char *	seq = (char *)SvPV_nolen(ST(1));
	HMM *	THIS;
	HMMReport *	RETVAL;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM") ) {
		THIS = (HMM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::_search() -- THIS is not an Algorithm::HMM object" );
		XSRETURN_UNDEF;
	};
#line 344 "HMM.xs"
        RETVAL = THIS->search(seq);
#line 1469 "HMM.c"
	ST(0) = sv_newmortal();
	if( RETVAL == NULL )	XSRETURN_UNDEF;
	sv_setref_pv( ST(0), "Algorithm::HMM::Report", (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM__train); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM__train)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items < 1)
       croak_xs_usage(cv,  "THIS, ...");
    {
	HMM *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM") ) {
		THIS = (HMM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::_train() -- THIS is not an Algorithm::HMM object" );
		XSRETURN_UNDEF;
	};
#line 351 "HMM.xs"
	char **seqs = (char **)malloc(sizeof(char *) * items);
        if(seqs == NULL) {
	  RETVAL = 0;
        } else {
	  int i;
	  for(i = 1; i < items; i++) {
	    SV *sv = (SV *)ST(i);
	    seqs[i - 1] = (char *)SvPV_nolen((SV *)sv);
	  }

	  RETVAL = THIS->train(seqs, items - 1);
	}
#line 1513 "HMM.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Algorithm__HMM_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Algorithm__HMM_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	HMM *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Algorithm::HMM") ) {
		THIS = (HMM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Algorithm::HMM::DESTROY() -- THIS is not an Algorithm::HMM object" );
		XSRETURN_UNDEF;
	};

	delete THIS;
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Algorithm__HMM); /* prototype to pass -Wmissing-prototypes */
XS(boot_Algorithm__HMM)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        newXS("Algorithm::HMM::Hit::Domain::hmm_domain_hit_new", XS_Algorithm__HMM__Hit__Domain_hmm_domain_hit_new, file);
        newXS("Algorithm::HMM::Hit::Domain::_getPValue", XS_Algorithm__HMM__Hit__Domain__getPValue, file);
        newXS("Algorithm::HMM::Hit::Domain::_setPValue", XS_Algorithm__HMM__Hit__Domain__setPValue, file);
        newXS("Algorithm::HMM::Hit::Domain::_getEValue", XS_Algorithm__HMM__Hit__Domain__getEValue, file);
        newXS("Algorithm::HMM::Hit::Domain::_setEValue", XS_Algorithm__HMM__Hit__Domain__setEValue, file);
        newXS("Algorithm::HMM::Hit::Domain::_getScore", XS_Algorithm__HMM__Hit__Domain__getScore, file);
        newXS("Algorithm::HMM::Hit::Domain::_setScore", XS_Algorithm__HMM__Hit__Domain__setScore, file);
        newXS("Algorithm::HMM::Hit::Domain::_getSeqFrom", XS_Algorithm__HMM__Hit__Domain__getSeqFrom, file);
        newXS("Algorithm::HMM::Hit::Domain::_setSeqFrom", XS_Algorithm__HMM__Hit__Domain__setSeqFrom, file);
        newXS("Algorithm::HMM::Hit::Domain::_getSeqTo", XS_Algorithm__HMM__Hit__Domain__getSeqTo, file);
        newXS("Algorithm::HMM::Hit::Domain::_setSeqTo", XS_Algorithm__HMM__Hit__Domain__setSeqTo, file);
        newXS("Algorithm::HMM::Hit::Domain::_getSeqLength", XS_Algorithm__HMM__Hit__Domain__getSeqLength, file);
        newXS("Algorithm::HMM::Hit::Domain::_setSeqLength", XS_Algorithm__HMM__Hit__Domain__setSeqLength, file);
        newXS("Algorithm::HMM::Hit::Domain::_getHMMFrom", XS_Algorithm__HMM__Hit__Domain__getHMMFrom, file);
        newXS("Algorithm::HMM::Hit::Domain::_setHMMFrom", XS_Algorithm__HMM__Hit__Domain__setHMMFrom, file);
        newXS("Algorithm::HMM::Hit::Domain::_getHMMTo", XS_Algorithm__HMM__Hit__Domain__getHMMTo, file);
        newXS("Algorithm::HMM::Hit::Domain::_setHMMTo", XS_Algorithm__HMM__Hit__Domain__setHMMTo, file);
        newXS("Algorithm::HMM::Hit::Domain::_getParentPValue", XS_Algorithm__HMM__Hit__Domain__getParentPValue, file);
        newXS("Algorithm::HMM::Hit::Domain::_setParentPValue", XS_Algorithm__HMM__Hit__Domain__setParentPValue, file);
        newXS("Algorithm::HMM::Hit::Domain::_getParentEValue", XS_Algorithm__HMM__Hit__Domain__getParentEValue, file);
        newXS("Algorithm::HMM::Hit::Domain::_setParentEValue", XS_Algorithm__HMM__Hit__Domain__setParentEValue, file);
        newXS("Algorithm::HMM::Hit::Domain::_getParentScore", XS_Algorithm__HMM__Hit__Domain__getParentScore, file);
        newXS("Algorithm::HMM::Hit::Domain::_setParentScore", XS_Algorithm__HMM__Hit__Domain__setParentScore, file);
        newXS("Algorithm::HMM::Hit::Global::hmm_global_hit_new", XS_Algorithm__HMM__Hit__Global_hmm_global_hit_new, file);
        newXS("Algorithm::HMM::Hit::Global::_getPValue", XS_Algorithm__HMM__Hit__Global__getPValue, file);
        newXS("Algorithm::HMM::Hit::Global::_setPValue", XS_Algorithm__HMM__Hit__Global__setPValue, file);
        newXS("Algorithm::HMM::Hit::Global::_getEValue", XS_Algorithm__HMM__Hit__Global__getEValue, file);
        newXS("Algorithm::HMM::Hit::Global::_setEValue", XS_Algorithm__HMM__Hit__Global__setEValue, file);
        newXS("Algorithm::HMM::Hit::Global::_getScore", XS_Algorithm__HMM__Hit__Global__getScore, file);
        newXS("Algorithm::HMM::Hit::Global::_setScore", XS_Algorithm__HMM__Hit__Global__setScore, file);
        newXS("Algorithm::HMM::Report::hmm_report_new", XS_Algorithm__HMM__Report_hmm_report_new, file);
        newXS("Algorithm::HMM::Report::_addGlobalHit", XS_Algorithm__HMM__Report__addGlobalHit, file);
        newXS("Algorithm::HMM::Report::_numGlobalHits", XS_Algorithm__HMM__Report__numGlobalHits, file);
        newXS("Algorithm::HMM::Report::_getGlobalHit", XS_Algorithm__HMM__Report__getGlobalHit, file);
        newXS("Algorithm::HMM::Report::_addDomainHit", XS_Algorithm__HMM__Report__addDomainHit, file);
        newXS("Algorithm::HMM::Report::_numDomainHits", XS_Algorithm__HMM__Report__numDomainHits, file);
        newXS("Algorithm::HMM::Report::_getDomainHit", XS_Algorithm__HMM__Report__getDomainHit, file);
        newXS("Algorithm::HMM::Report::DESTROY", XS_Algorithm__HMM__Report_DESTROY, file);
        newXS("Algorithm::HMM::hmm_new", XS_Algorithm__HMM_hmm_new, file);
        newXS("Algorithm::HMM::_save", XS_Algorithm__HMM__save, file);
        newXS("Algorithm::HMM::_load", XS_Algorithm__HMM__load, file);
        newXS("Algorithm::HMM::_modelLoaded", XS_Algorithm__HMM__modelLoaded, file);
        newXS("Algorithm::HMM::_getDoForward", XS_Algorithm__HMM__getDoForward, file);
        newXS("Algorithm::HMM::_setDoForward", XS_Algorithm__HMM__setDoForward, file);
        newXS("Algorithm::HMM::_getDoNull2", XS_Algorithm__HMM__getDoNull2, file);
        newXS("Algorithm::HMM::_setDoNull2", XS_Algorithm__HMM__setDoNull2, file);
        newXS("Algorithm::HMM::_search", XS_Algorithm__HMM__search, file);
        newXS("Algorithm::HMM::_train", XS_Algorithm__HMM__train, file);
        newXS("Algorithm::HMM::DESTROY", XS_Algorithm__HMM_DESTROY, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

