/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of modhmm.xs. Do not edit this file, edit modhmm.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "modhmm.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"
#include "modhmm0.92b/structs.h"

#line 16 "modhmm.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 68 "modhmm.c"

XS(XS_Bio__Tools__PSort__ModHMM_find_helices); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__ModHMM_find_helices)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "seq, hmmfile, repfile, path");
    {
	char *	seq = (char *)SvPV_nolen(ST(0));
	char *	hmmfile = (char *)SvPV_nolen(ST(1));
	char *	repfile = (char *)SvPV_nolen(ST(2));
	char *	path = (char *)SvPV_nolen(ST(3));
	int	RETVAL;
	dXSTARG;

	RETVAL = find_helices(seq, hmmfile, repfile, path);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bio__Tools__PSort__ModHMM_get_helices); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__ModHMM_get_helices)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "seq, hmmfile, repfile, path");
    {
	char *	seq = (char *)SvPV_nolen(ST(0));
	char *	hmmfile = (char *)SvPV_nolen(ST(1));
	char *	repfile = (char *)SvPV_nolen(ST(2));
	char *	path = (char *)SvPV_nolen(ST(3));
	Bio__Tools__PSort__ModHMM__HelixSites *	RETVAL;

	RETVAL = get_helices(seq, hmmfile, repfile, path);
	ST(0) = sv_newmortal();
	sv_setref_pv(ST(0), "Bio::Tools::PSort::ModHMM::HelixSitesPtr", (void*)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bio__Tools__PSort__ModHMM__HelixSitesPtr_count); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__ModHMM__HelixSitesPtr_count)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "hSites");
    {
	Bio__Tools__PSort__ModHMM__HelixSites *	hSites;
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Bio::Tools::PSort::ModHMM::HelixSitesPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    hSites = INT2PTR(Bio__Tools__PSort__ModHMM__HelixSites *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Bio::Tools::PSort::ModHMM::HelixSitesPtr::count",
			"hSites", "Bio::Tools::PSort::ModHMM::HelixSitesPtr");

	RETVAL = helix_count(hSites);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bio__Tools__PSort__ModHMM__HelixSitesPtr_start); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__ModHMM__HelixSitesPtr_start)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "hSites, helix");
    {
	Bio__Tools__PSort__ModHMM__HelixSites *	hSites;
	int	helix = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Bio::Tools::PSort::ModHMM::HelixSitesPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    hSites = INT2PTR(Bio__Tools__PSort__ModHMM__HelixSites *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Bio::Tools::PSort::ModHMM::HelixSitesPtr::start",
			"hSites", "Bio::Tools::PSort::ModHMM::HelixSitesPtr");

	RETVAL = helix_start(hSites, helix);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bio__Tools__PSort__ModHMM__HelixSitesPtr_end); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__ModHMM__HelixSitesPtr_end)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "hSites, helix");
    {
	Bio__Tools__PSort__ModHMM__HelixSites *	hSites;
	int	helix = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;

	if (SvROK(ST(0)) && sv_derived_from(ST(0), "Bio::Tools::PSort::ModHMM::HelixSitesPtr")) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    hSites = INT2PTR(Bio__Tools__PSort__ModHMM__HelixSites *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not of type %s",
			"Bio::Tools::PSort::ModHMM::HelixSitesPtr::end",
			"hSites", "Bio::Tools::PSort::ModHMM::HelixSitesPtr");

	RETVAL = helix_end(hSites, helix);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bio__Tools__PSort__ModHMM__HelixSitesPtr_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__ModHMM__HelixSitesPtr_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "hSites");
    {
	Bio__Tools__PSort__ModHMM__HelixSites *	hSites;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    hSites = INT2PTR(Bio__Tools__PSort__ModHMM__HelixSites *,tmp);
	}
	else
	    Perl_croak(aTHX_ "%s: %s is not a reference",
			"Bio::Tools::PSort::ModHMM::HelixSitesPtr::DESTROY",
			"hSites");

	helix_DESTROY(hSites);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Bio__Tools__PSort__ModHMM); /* prototype to pass -Wmissing-prototypes */
XS(boot_Bio__Tools__PSort__ModHMM)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        newXS("Bio::Tools::PSort::ModHMM::find_helices", XS_Bio__Tools__PSort__ModHMM_find_helices, file);
        newXS("Bio::Tools::PSort::ModHMM::get_helices", XS_Bio__Tools__PSort__ModHMM_get_helices, file);
        (void)newXSproto_portable("Bio::Tools::PSort::ModHMM::HelixSitesPtr::count", XS_Bio__Tools__PSort__ModHMM__HelixSitesPtr_count, file, "$");
        (void)newXSproto_portable("Bio::Tools::PSort::ModHMM::HelixSitesPtr::start", XS_Bio__Tools__PSort__ModHMM__HelixSitesPtr_start, file, "$$");
        (void)newXSproto_portable("Bio::Tools::PSort::ModHMM::HelixSitesPtr::end", XS_Bio__Tools__PSort__ModHMM__HelixSitesPtr_end, file, "$$");
        (void)newXSproto_portable("Bio::Tools::PSort::ModHMM::HelixSitesPtr::DESTROY", XS_Bio__Tools__PSort__ModHMM__HelixSitesPtr_DESTROY, file, "$");
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

