/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of SVMLoc.xs. Do not edit this file, edit SVMLoc.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "SVMLoc.xs"
#include <vector>
#include <map>

#include "bindings.h"

#ifdef __cplusplus
extern "C" {
#endif

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#ifdef __cplusplus
}
#endif

DataSet *_new_dataset(double l) {

  return new DataSet(l);
}

SVM *_new_svm(int st, int kt, int d, double g, double c0, double C,
	      double nu, double e) {

  return new SVM(st, kt, d, g, c0, C, nu, e);
}

#line 39 "SVMLoc.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 91 "SVMLoc.c"

XS(XS_Bio__Tools__PSort__SVMLoc__DataSet__new_dataset); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__SVMLoc__DataSet__new_dataset)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "l");
    {
	double	l = (double)SvNV(ST(0));
	DataSet *	RETVAL;

	RETVAL = _new_dataset(l);
	ST(0) = sv_newmortal();
	if( RETVAL == NULL )	XSRETURN_UNDEF;
	sv_setref_pv( ST(0), "Bio::Tools::PSort::SVMLoc::DataSet", (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Bio__Tools__PSort__SVMLoc__DataSet__getLabel); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__SVMLoc__DataSet__getLabel)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	DataSet *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Bio::Tools::PSort::SVMLoc::DataSet") ) {
		THIS = (DataSet *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Bio::Tools::PSort::SVMLoc::DataSet::_getLabel() -- THIS is not an Bio::Tools::PSort::SVMLoc::DataSet object" );
		XSRETURN_UNDEF;
	};
#line 38 "SVMLoc.xs"
      RETVAL = THIS->getLabel();
#line 140 "SVMLoc.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bio__Tools__PSort__SVMLoc__DataSet__setLabel); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__SVMLoc__DataSet__setLabel)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, l");
    {
	double	l = (double)SvNV(ST(1));
	DataSet *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Bio::Tools::PSort::SVMLoc::DataSet") ) {
		THIS = (DataSet *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Bio::Tools::PSort::SVMLoc::DataSet::_setLabel() -- THIS is not an Bio::Tools::PSort::SVMLoc::DataSet object" );
		XSRETURN_UNDEF;
	};
#line 46 "SVMLoc.xs"
      THIS->setLabel(l);
#line 169 "SVMLoc.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Bio__Tools__PSort__SVMLoc__DataSet__getAttribute); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__SVMLoc__DataSet__getAttribute)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, k");
    {
	int	k = (int)SvIV(ST(1));
	DataSet *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Bio::Tools::PSort::SVMLoc::DataSet") ) {
		THIS = (DataSet *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Bio::Tools::PSort::SVMLoc::DataSet::_getAttribute() -- THIS is not an Bio::Tools::PSort::SVMLoc::DataSet object" );
		XSRETURN_UNDEF;
	};
#line 52 "SVMLoc.xs"
      RETVAL = THIS->getAttribute(k);
#line 199 "SVMLoc.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bio__Tools__PSort__SVMLoc__DataSet__setAttribute); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__SVMLoc__DataSet__setAttribute)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 3)
       croak_xs_usage(cv,  "THIS, k, v");
    {
	int	k = (int)SvIV(ST(1));
	double	v = (double)SvNV(ST(2));
	DataSet *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Bio::Tools::PSort::SVMLoc::DataSet") ) {
		THIS = (DataSet *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Bio::Tools::PSort::SVMLoc::DataSet::_setAttribute() -- THIS is not an Bio::Tools::PSort::SVMLoc::DataSet object" );
		XSRETURN_UNDEF;
	};
#line 61 "SVMLoc.xs"
      THIS->setAttribute(k,v);
#line 229 "SVMLoc.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Bio__Tools__PSort__SVMLoc__DataSet_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__SVMLoc__DataSet_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	DataSet *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Bio::Tools::PSort::SVMLoc::DataSet") ) {
		THIS = (DataSet *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Bio::Tools::PSort::SVMLoc::DataSet::DESTROY() -- THIS is not an Bio::Tools::PSort::SVMLoc::DataSet object" );
		XSRETURN_UNDEF;
	};

	delete THIS;
    }
    XSRETURN_EMPTY;
}


XS(XS_Bio__Tools__PSort__SVMLoc__new_svm); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__SVMLoc__new_svm)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 8)
       croak_xs_usage(cv,  "st, kt, d, g, c0, C, nu, e");
    {
	int	st = (int)SvIV(ST(0));
	int	kt = (int)SvIV(ST(1));
	int	d = (int)SvIV(ST(2));
	double	g = (double)SvNV(ST(3));
	double	c0 = (double)SvNV(ST(4));
	double	C = (double)SvNV(ST(5));
	double	nu = (double)SvNV(ST(6));
	double	e = (double)SvNV(ST(7));
	SVM *	RETVAL;

	RETVAL = _new_svm(st, kt, d, g, c0, C, nu, e);
	ST(0) = sv_newmortal();
	if( RETVAL == NULL )	XSRETURN_UNDEF;
	sv_setref_pv( ST(0), "Bio::Tools::PSort::SVMLoc", (void*)RETVAL );

    }
    XSRETURN(1);
}


XS(XS_Bio__Tools__PSort__SVMLoc__classify); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__SVMLoc__classify)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, seq");
    {
	char *	seq = (char *)SvPV_nolen(ST(1));
	SVM *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Bio::Tools::PSort::SVMLoc") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Bio::Tools::PSort::SVMLoc::_classify() -- THIS is not an Bio::Tools::PSort::SVMLoc object, received ST(0)" );
		XSRETURN_UNDEF;
	};
#line 83 "SVMLoc.xs"
      RETVAL = THIS->classify(seq);
#line 316 "SVMLoc.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bio__Tools__PSort__SVMLoc__loadModel); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__SVMLoc__loadModel)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, filename");
    {
	char *	filename = (char *)SvPV_nolen(ST(1));
	SVM *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Bio::Tools::PSort::SVMLoc") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Bio::Tools::PSort::SVMLoc::_loadModel() -- THIS is not an Bio::Tools::PSort::SVMLoc object, received ST(0)" );
		XSRETURN_UNDEF;
	};
#line 91 "SVMLoc.xs"
      RETVAL = THIS->loadModel(filename);
#line 347 "SVMLoc.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bio__Tools__PSort__SVMLoc__loadFreqPattern); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__SVMLoc__loadFreqPattern)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, filename");
    {
	char *	filename = (char *)SvPV_nolen(ST(1));
	SVM *	THIS;
	int	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Bio::Tools::PSort::SVMLoc") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Bio::Tools::PSort::SVMLoc::_loadFreqPattern() -- THIS is not an Bio::Tools::PSort::SVMLoc object, received ST(0)" );
		XSRETURN_UNDEF;
	};
#line 99 "SVMLoc.xs"
      RETVAL = THIS->loadFreqPattern(filename);
#line 378 "SVMLoc.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bio__Tools__PSort__SVMLoc__predict); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__SVMLoc__predict)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "THIS, ds");
    {
	DataSet *	ds;
	SVM *	THIS;
	double	RETVAL;
	dXSTARG;

	if( sv_isobject(ST(1)) && sv_isa(ST(1), "Bio::Tools::PSort::SVMLoc::DataSet") ) {
		ds = (DataSet *)SvIV((SV*)SvRV( ST(1) ));
	} else {
		warn( "Bio::Tools::PSort::SVMLoc::_predict() -- ds is not an Bio::Tools::PSort::SVMLoc::DataSet object" );
		XSRETURN_UNDEF;
	};

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Bio::Tools::PSort::SVMLoc") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Bio::Tools::PSort::SVMLoc::_predict() -- THIS is not an Bio::Tools::PSort::SVMLoc object, received ST(0)" );
		XSRETURN_UNDEF;
	};
#line 107 "SVMLoc.xs"
      RETVAL = THIS->predict(ds);
#line 416 "SVMLoc.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Bio__Tools__PSort__SVMLoc_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Bio__Tools__PSort__SVMLoc_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    {
	SVM *	THIS;

	if( sv_isobject(ST(0)) && sv_isa(ST(0), "Bio::Tools::PSort::SVMLoc") ) {
		THIS = (SVM *)SvIV((SV*)SvRV( ST(0) ));
	} else {
		warn( "Bio::Tools::PSort::SVMLoc::DESTROY() -- THIS is not an Bio::Tools::PSort::SVMLoc object, received ST(0)" );
		XSRETURN_UNDEF;
	};

	delete THIS;
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Bio__Tools__PSort__SVMLoc); /* prototype to pass -Wmissing-prototypes */
XS(boot_Bio__Tools__PSort__SVMLoc)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        newXS("Bio::Tools::PSort::SVMLoc::DataSet::_new_dataset", XS_Bio__Tools__PSort__SVMLoc__DataSet__new_dataset, file);
        newXS("Bio::Tools::PSort::SVMLoc::DataSet::_getLabel", XS_Bio__Tools__PSort__SVMLoc__DataSet__getLabel, file);
        newXS("Bio::Tools::PSort::SVMLoc::DataSet::_setLabel", XS_Bio__Tools__PSort__SVMLoc__DataSet__setLabel, file);
        newXS("Bio::Tools::PSort::SVMLoc::DataSet::_getAttribute", XS_Bio__Tools__PSort__SVMLoc__DataSet__getAttribute, file);
        newXS("Bio::Tools::PSort::SVMLoc::DataSet::_setAttribute", XS_Bio__Tools__PSort__SVMLoc__DataSet__setAttribute, file);
        newXS("Bio::Tools::PSort::SVMLoc::DataSet::DESTROY", XS_Bio__Tools__PSort__SVMLoc__DataSet_DESTROY, file);
        newXS("Bio::Tools::PSort::SVMLoc::_new_svm", XS_Bio__Tools__PSort__SVMLoc__new_svm, file);
        newXS("Bio::Tools::PSort::SVMLoc::_classify", XS_Bio__Tools__PSort__SVMLoc__classify, file);
        newXS("Bio::Tools::PSort::SVMLoc::_loadModel", XS_Bio__Tools__PSort__SVMLoc__loadModel, file);
        newXS("Bio::Tools::PSort::SVMLoc::_loadFreqPattern", XS_Bio__Tools__PSort__SVMLoc__loadFreqPattern, file);
        newXS("Bio::Tools::PSort::SVMLoc::_predict", XS_Bio__Tools__PSort__SVMLoc__predict, file);
        newXS("Bio::Tools::PSort::SVMLoc::DESTROY", XS_Bio__Tools__PSort__SVMLoc_DESTROY, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

